global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "envoy"
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["envoy:9901"]

  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:80"]

  - job_name: "checkout"
    static_configs:
      - targets: ["checkout:80"]

  - job_name: "product"
    static_configs:
      - targets: ["product:80"]

